/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author Admin
 */
public class ListMoney extends javax.swing.JFrame {

    /**
     * Creates new form ListMoney
     */
    public ListMoney() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jBtn1K = new javax.swing.JButton();
        jBtn2K = new javax.swing.JButton();
        jBtn5K = new javax.swing.JButton();
        jBtn10K = new javax.swing.JButton();
        jBtn20K = new javax.swing.JButton();
        jBtn50K = new javax.swing.JButton();
        jBtn100K = new javax.swing.JButton();
        jBtn200K = new javax.swing.JButton();
        jBtn500K = new javax.swing.JButton();

        jButton9.setText("jButton9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        jBtn1K.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn1K.setText("1.000 VNĐ");
        getContentPane().add(jBtn1K);

        jBtn2K.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn2K.setText("2.000 VNĐ");
        getContentPane().add(jBtn2K);

        jBtn5K.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn5K.setText("5.000 VNĐ");
        getContentPane().add(jBtn5K);

        jBtn10K.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn10K.setText("10.000 VNĐ");
        getContentPane().add(jBtn10K);

        jBtn20K.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn20K.setText("20.000 VNĐ");
        getContentPane().add(jBtn20K);

        jBtn50K.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn50K.setText("50.000 VNĐ");
        getContentPane().add(jBtn50K);

        jBtn100K.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn100K.setText("100.000 VNĐ");
        getContentPane().add(jBtn100K);

        jBtn200K.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn200K.setText("200.000 VNĐ");
        getContentPane().add(jBtn200K);

        jBtn500K.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtn500K.setText("500.000 VNĐ");
        getContentPane().add(jBtn500K);

        setSize(new java.awt.Dimension(763, 362));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn100K;
    private javax.swing.JButton jBtn10K;
    private javax.swing.JButton jBtn1K;
    private javax.swing.JButton jBtn200K;
    private javax.swing.JButton jBtn20K;
    private javax.swing.JButton jBtn2K;
    private javax.swing.JButton jBtn500K;
    private javax.swing.JButton jBtn50K;
    private javax.swing.JButton jBtn5K;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
